server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  profiles:
    active: native  #启用本地的配置文件；也可以改为git，从git上拉取配置
  cloud:
    config:
      server:
        native:
          search-locations: classpath:configs/{profile} #本地配置文件的路径，profile在客户端配置文件中配置
          #search-locations: file:/d:/configs/{profile} #也可以从本地文件中读取
        git:
          uri:  https://github.com/ChenJie666/microservicecloud-config
          #uri:  git@github.com:ChenJie666/microservicecloud-config
          default-label: master #如果配置服务器客户端没有设置，则默认是master
          force-pull: true

#通过：
#http://config-3344.com:3344/application-dev.yml
#http://config-3344.com:3344/master/application-dev.yml
#http://config-3344.com:3344/application/dev/master
#进行配置文件的查看

eureka:
  client:
    service-url:
      default-zone: http://root:abc123@eureka1.com/eureka/  #注册中心的地址（需要注册中心的账号密码）
    registry-fetch-interval-seconds: 5  #Eureka Client隔多久从注册中心拉取注册服务的信息
  instance:
    lease-expiration-duration-in-seconds: 15 #服务过期时间
    lease-renewal-interval-in-seconds: 5 #发送心跳时间
    prefer-ip-address: true #域名显示为ip而非主机名

management:  #TODO ???
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:  #TODO ???
  level:
    root: info
  file: logs/${spring.application.name}.log