logging:
  level:
    root: info  #root级别的日志级别是info
    com.hxr.springcloud: debug  #自定义包下的日志级别是debug
  file: logs/${spring.application.name}.log #自定义日志文件输出
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.148.11:3307/microservice-oauth2?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: abc123
    #此处可以用hikari连接池代替自带的连接池
  rabbitmq:
    host: 116.62.148.11
    port: 5672
    username: user
    password: user
    virtual-host: /vhost_mmr
  redis:
    host: 116.62.148.11
    port: 6380
    password: #没设置密码可以空着
    timeout: 10s

mybatis:
  type-aliases-package: com.hxr.springcloud.entities  #实体类所在的包
  mapper-locations: classpath:/mybatis/mapper/* #mapper配置文件所在的路径,将复杂的sql查询写在xml文件中；简单的sql查询写在Dao层的注解中
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰功能，即user_name会自动匹配userName


