#服务的mybatis设置
mybatis:
  type-aliases-package: com.hxr.springcloud.entities # 所有Entity别名类所在的包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml # mapper映射文件（通过mapper.xml文件或注释完成数据库操作）
#服务的数据库连接设置
spring:
  application:
    name: microservicecloud-dept  # 对外暴露的微服务名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据库操作类型
    driver-class-name: org.gjt.mm.mysql.Driver  # mysql驱动包
    url: jdbc:mysql://116.62.148.11:3307/cloudDB01  # 数据库名称
    username: root
    password: abc123
    dbcp2:
      min-idle: 5 #数据库连接池的最小维持连接数
      initial-size: 5 #初始化连接数
      max-total: 5 #最大连接数
      max-wait-millis: 200 #等待连接获取的最大超时时间
